spring.application.name=projps2
server.error.include-message=always

# Configurações do Banco de Dados H2 (Em Memória)
spring.datasource.url=jdbc:h2:mem:projps2db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Pede para o JPA/Hibernate criar as tabelas automaticamente baseado nas suas Entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilita o console do H2 para você ver o banco pelo navegador (opcional, mas muito útil)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console